//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PSWebApp.PeopleSoft {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PSRemoteInterfaceBinding", Namespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(list))]
    public partial class PeopleSoftService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback confirmAVCOperationCompleted;
        
        private System.Threading.SendOrPostCallback confirmAllAVCOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFSSUEmployeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFSSUEmployees2OperationCompleted;
        
        private System.Threading.SendOrPostCallback getPenfaceEmployeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPenfaceFnanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PeopleSoftService() {
            this.Url = global::PSWebApp.Properties.Settings.Default.PSWebApp_PeopleSoft_PeopleSoftService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event confirmAVCCompletedEventHandler confirmAVCCompleted;
        
        /// <remarks/>
        public event confirmAllAVCCompletedEventHandler confirmAllAVCCompleted;
        
        /// <remarks/>
        public event getEmployeeCompletedEventHandler getEmployeeCompleted;
        
        /// <remarks/>
        public event getFSSUEmployeesCompletedEventHandler getFSSUEmployeesCompleted;
        
        /// <remarks/>
        public event getFSSUEmployees2CompletedEventHandler getFSSUEmployees2Completed;
        
        /// <remarks/>
        public event getPenfaceEmployeesCompletedEventHandler getPenfaceEmployeesCompleted;
        
        /// <remarks/>
        public event getPenfaceFnanceCompletedEventHandler getPenfaceFnanceCompleted;
        
        /// <remarks/>
        public event getStatusCompletedEventHandler getStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL", ResponseNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public PSObject confirmAVC(string String_1) {
            object[] results = this.Invoke("confirmAVC", new object[] {
                        String_1});
            return ((PSObject)(results[0]));
        }
        
        /// <remarks/>
        public void confirmAVCAsync(string String_1) {
            this.confirmAVCAsync(String_1, null);
        }
        
        /// <remarks/>
        public void confirmAVCAsync(string String_1, object userState) {
            if ((this.confirmAVCOperationCompleted == null)) {
                this.confirmAVCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmAVCOperationCompleted);
            }
            this.InvokeAsync("confirmAVC", new object[] {
                        String_1}, this.confirmAVCOperationCompleted, userState);
        }
        
        private void OnconfirmAVCOperationCompleted(object arg) {
            if ((this.confirmAVCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.confirmAVCCompleted(this, new confirmAVCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL", ResponseNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public arrayList confirmAllAVC() {
            object[] results = this.Invoke("confirmAllAVC", new object[0]);
            return ((arrayList)(results[0]));
        }
        
        /// <remarks/>
        public void confirmAllAVCAsync() {
            this.confirmAllAVCAsync(null);
        }
        
        /// <remarks/>
        public void confirmAllAVCAsync(object userState) {
            if ((this.confirmAllAVCOperationCompleted == null)) {
                this.confirmAllAVCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmAllAVCOperationCompleted);
            }
            this.InvokeAsync("confirmAllAVC", new object[0], this.confirmAllAVCOperationCompleted, userState);
        }
        
        private void OnconfirmAllAVCOperationCompleted(object arg) {
            if ((this.confirmAllAVCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.confirmAllAVCCompleted(this, new confirmAllAVCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL", ResponseNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public FSSUEmployees getEmployee(string String_1) {
            object[] results = this.Invoke("getEmployee", new object[] {
                        String_1});
            return ((FSSUEmployees)(results[0]));
        }
        
        /// <remarks/>
        public void getEmployeeAsync(string String_1) {
            this.getEmployeeAsync(String_1, null);
        }
        
        /// <remarks/>
        public void getEmployeeAsync(string String_1, object userState) {
            if ((this.getEmployeeOperationCompleted == null)) {
                this.getEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmployeeOperationCompleted);
            }
            this.InvokeAsync("getEmployee", new object[] {
                        String_1}, this.getEmployeeOperationCompleted, userState);
        }
        
        private void OngetEmployeeOperationCompleted(object arg) {
            if ((this.getEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEmployeeCompleted(this, new getEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL", ResponseNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public Object getFSSUEmployees(string String_1) {
            object[] results = this.Invoke("getFSSUEmployees", new object[] {
                        String_1});
            return ((Object)(results[0]));
        }
        
        /// <remarks/>
        public void getFSSUEmployeesAsync(string String_1) {
            this.getFSSUEmployeesAsync(String_1, null);
        }
        
        /// <remarks/>
        public void getFSSUEmployeesAsync(string String_1, object userState) {
            if ((this.getFSSUEmployeesOperationCompleted == null)) {
                this.getFSSUEmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFSSUEmployeesOperationCompleted);
            }
            this.InvokeAsync("getFSSUEmployees", new object[] {
                        String_1}, this.getFSSUEmployeesOperationCompleted, userState);
        }
        
        private void OngetFSSUEmployeesOperationCompleted(object arg) {
            if ((this.getFSSUEmployeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFSSUEmployeesCompleted(this, new getFSSUEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL", ResponseNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public PSObject getFSSUEmployees2(string String_1, string String_2) {
            object[] results = this.Invoke("getFSSUEmployees2", new object[] {
                        String_1,
                        String_2});
            return ((PSObject)(results[0]));
        }
        
        /// <remarks/>
        public void getFSSUEmployees2Async(string String_1, string String_2) {
            this.getFSSUEmployees2Async(String_1, String_2, null);
        }
        
        /// <remarks/>
        public void getFSSUEmployees2Async(string String_1, string String_2, object userState) {
            if ((this.getFSSUEmployees2OperationCompleted == null)) {
                this.getFSSUEmployees2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFSSUEmployees2OperationCompleted);
            }
            this.InvokeAsync("getFSSUEmployees2", new object[] {
                        String_1,
                        String_2}, this.getFSSUEmployees2OperationCompleted, userState);
        }
        
        private void OngetFSSUEmployees2OperationCompleted(object arg) {
            if ((this.getFSSUEmployees2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFSSUEmployees2Completed(this, new getFSSUEmployees2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL", ResponseNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public arrayList getPenfaceEmployees(string String_1) {
            object[] results = this.Invoke("getPenfaceEmployees", new object[] {
                        String_1});
            return ((arrayList)(results[0]));
        }
        
        /// <remarks/>
        public void getPenfaceEmployeesAsync(string String_1) {
            this.getPenfaceEmployeesAsync(String_1, null);
        }
        
        /// <remarks/>
        public void getPenfaceEmployeesAsync(string String_1, object userState) {
            if ((this.getPenfaceEmployeesOperationCompleted == null)) {
                this.getPenfaceEmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPenfaceEmployeesOperationCompleted);
            }
            this.InvokeAsync("getPenfaceEmployees", new object[] {
                        String_1}, this.getPenfaceEmployeesOperationCompleted, userState);
        }
        
        private void OngetPenfaceEmployeesOperationCompleted(object arg) {
            if ((this.getPenfaceEmployeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPenfaceEmployeesCompleted(this, new getPenfaceEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL", ResponseNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public PenfaceFinance getPenfaceFnance() {
            object[] results = this.Invoke("getPenfaceFnance", new object[0]);
            return ((PenfaceFinance)(results[0]));
        }
        
        /// <remarks/>
        public void getPenfaceFnanceAsync() {
            this.getPenfaceFnanceAsync(null);
        }
        
        /// <remarks/>
        public void getPenfaceFnanceAsync(object userState) {
            if ((this.getPenfaceFnanceOperationCompleted == null)) {
                this.getPenfaceFnanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPenfaceFnanceOperationCompleted);
            }
            this.InvokeAsync("getPenfaceFnance", new object[0], this.getPenfaceFnanceOperationCompleted, userState);
        }
        
        private void OngetPenfaceFnanceOperationCompleted(object arg) {
            if ((this.getPenfaceFnanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPenfaceFnanceCompleted(this, new getPenfaceFnanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL", ResponseNamespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public Status getStatus() {
            object[] results = this.Invoke("getStatus", new object[0]);
            return ((Status)(results[0]));
        }
        
        /// <remarks/>
        public void getStatusAsync() {
            this.getStatusAsync(null);
        }
        
        /// <remarks/>
        public void getStatusAsync(object userState) {
            if ((this.getStatusOperationCompleted == null)) {
                this.getStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatusOperationCompleted);
            }
            this.InvokeAsync("getStatus", new object[0], this.getStatusOperationCompleted, userState);
        }
        
        private void OngetStatusOperationCompleted(object arg) {
            if ((this.getStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatusCompleted(this, new getStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
    public partial class PSObject {
        
        private double dedCurField;
        
        private string statusField;
        
        /// <remarks/>
        public double dedCur {
            get {
                return this.dedCurField;
            }
            set {
                this.dedCurField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(arrayList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://java.sun.com/jax-rpc-ri/internal")]
    public partial class list {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://java.sun.com/jax-rpc-ri/internal")]
    public partial class arrayList : list {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
    public partial class Status {
        
        private string idField;
        
        private string statusField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
    public partial class PenfaceFinance {
        
        private string avcContField;
        
        private string emplidField;
        
        private string employeeContField;
        
        private string employeeContOrigField;
        
        private string employerContField;
        
        private string nameField;
        
        private string payEndDtField;
        
        /// <remarks/>
        public string avcCont {
            get {
                return this.avcContField;
            }
            set {
                this.avcContField = value;
            }
        }
        
        /// <remarks/>
        public string emplid {
            get {
                return this.emplidField;
            }
            set {
                this.emplidField = value;
            }
        }
        
        /// <remarks/>
        public string employeeCont {
            get {
                return this.employeeContField;
            }
            set {
                this.employeeContField = value;
            }
        }
        
        /// <remarks/>
        public string employeeContOrig {
            get {
                return this.employeeContOrigField;
            }
            set {
                this.employeeContOrigField = value;
            }
        }
        
        /// <remarks/>
        public string employerCont {
            get {
                return this.employerContField;
            }
            set {
                this.employerContField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string payEndDt {
            get {
                return this.payEndDtField;
            }
            set {
                this.payEndDtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://localhost:8080/PeopelSoft/PeopelSoft?WSDL")]
    public partial class FSSUEmployees {
        
        private string addlNBRField;
        
        private string benefitPlanField;
        
        private string dedClassField;
        
        private string dedCurField;
        
        private string emplidField;
        
        private string employerContField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string nationalIDField;
        
        private string payEndDtField;
        
        /// <remarks/>
        public string addlNBR {
            get {
                return this.addlNBRField;
            }
            set {
                this.addlNBRField = value;
            }
        }
        
        /// <remarks/>
        public string benefitPlan {
            get {
                return this.benefitPlanField;
            }
            set {
                this.benefitPlanField = value;
            }
        }
        
        /// <remarks/>
        public string dedClass {
            get {
                return this.dedClassField;
            }
            set {
                this.dedClassField = value;
            }
        }
        
        /// <remarks/>
        public string dedCur {
            get {
                return this.dedCurField;
            }
            set {
                this.dedCurField = value;
            }
        }
        
        /// <remarks/>
        public string emplid {
            get {
                return this.emplidField;
            }
            set {
                this.emplidField = value;
            }
        }
        
        /// <remarks/>
        public string employerCont {
            get {
                return this.employerContField;
            }
            set {
                this.employerContField = value;
            }
        }
        
        /// <remarks/>
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string nationalID {
            get {
                return this.nationalIDField;
            }
            set {
                this.nationalIDField = value;
            }
        }
        
        /// <remarks/>
        public string payEndDt {
            get {
                return this.payEndDtField;
            }
            set {
                this.payEndDtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void confirmAVCCompletedEventHandler(object sender, confirmAVCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class confirmAVCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal confirmAVCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PSObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PSObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void confirmAllAVCCompletedEventHandler(object sender, confirmAllAVCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class confirmAllAVCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal confirmAllAVCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public arrayList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((arrayList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getEmployeeCompletedEventHandler(object sender, getEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FSSUEmployees Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FSSUEmployees)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getFSSUEmployeesCompletedEventHandler(object sender, getFSSUEmployeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFSSUEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFSSUEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public arrayList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((arrayList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getFSSUEmployees2CompletedEventHandler(object sender, getFSSUEmployees2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFSSUEmployees2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFSSUEmployees2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PSObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PSObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getPenfaceEmployeesCompletedEventHandler(object sender, getPenfaceEmployeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPenfaceEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPenfaceEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public arrayList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((arrayList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getPenfaceFnanceCompletedEventHandler(object sender, getPenfaceFnanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPenfaceFnanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPenfaceFnanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PenfaceFinance Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PenfaceFinance)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getStatusCompletedEventHandler(object sender, getStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Status Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591